<h1 style='text-align: center;'>How to Use Python Descripstats Package</h1>
<h3 style='text-align: center;'>Shouke Wei, Ph.D. Professor<sup>1</sup></h3>
<h5 style='text-align: center;'><sup>1</sup> Deepsim Intelligence Technology Inc, BC V2T0G9, Abbotsford, Canada</h5>
<h5 style='text-align: center;'>Email: shouke.wei@deepsim.ca</h5>

## 1. Brief introduction of the package

For numeric data, the `describe( )` function of Python Pandas provides a very convenient method to generate a general summary table of descriptive Statistics. However, the result's index only include `count`, `mean`, `std`, `min`, `max` as well as `lower`, `50` and `upper percentiles`. By default, the lower percentile is `25`, the upper percentile is `75`, and the `50` percentile is the same as the median.

In most cases, such as writing a scientific and data analysis report, and journal paper, we need more statistic indices than these default ones, such as mean absolute deviation (`mad`), `variance`, standard error of the mean (`sem`), `sum`, `skewness`, `kurtosis`, etc. Pandas also provides methods to calculate them, but we have to write a code snippet to add them to the summary table of the `describe( )` function.

This is a small package, which help you add more descriptive statistic measures to the default `describe()` of Pandas, which include:  
   - mad: mean absolute deviation
   - variance: variance
   - sem: standard error of the mean
   - sum: sum
   - skewness: skewness
   - kurtosis: kurtosis

### Method:
`Describe(data)`  
   - **Parameters**:   
      - data: data in NumPy array or Pandas DataFrame  
   - **Return**:  
       - stats: the descriptive statistics

## 2. Example

### (1) Import the packages
You can import the package with:
```python
from descripstats import Describe
```
then use the `Describe()` directly. Or 
```python
import descripstats as ds
```
then use `ds.Describe()`

We use the second method in this example as follows:

In [1]:
import pandas as pd
import descripstats as ds

### (2) Read data to Pandas DataFrame

In [2]:
# example local DataFrame (stable example for docs)
df = pd.DataFrame({"A": [1, 2, 3, 4, 5], "B": [10, 20, 30, 40, 50]})

# display the first rows
df.head()

   A   B
0  1  10
1  2  20
2  3  30
3  4  40
4  5  50

### (3) Display the default descriptive statistic measures of Pandas
First, let's use the `describe()` function of Pandas so that you can clearly see what measures added in this package later.

In [3]:
df.describe()

              A          B
count  5.000000   5.000000
mean   3.000000  30.000000
std    1.581139  15.811388
min    1.000000  10.000000
25%    2.000000  20.000000
50%    3.000000  30.000000
75%    4.000000  40.000000
max    5.000000  50.000000

### (4) Descriptive statistic measures added by this package
Now, let's use the function of the package.

In [4]:
ds.Describe(df)

                  A           B
count      5.000000    5.000000
mean       3.000000   30.000000
std        1.581139   15.811388
min        1.000000   10.000000
25%        2.000000   20.000000
50%        3.000000   30.000000
75%        4.000000   40.000000
max        5.000000   50.000000
mad        1.200000   12.000000
variance   2.500000  250.000000
sem        0.707107    7.071068
sum       15.000000  150.000000
skewness   0.000000    0.000000
kurtosis  -1.200000   -1.200000

### (5) Remove some of them
You can remove one or more of them you do not want through the following way.

In [5]:
stats = ds.Describe(df)

#### (i) remove one
For example, you do not want to include `mad` (mean absolute deviation) in the summary table

In [6]:
stats.drop('mad')

                  A           B
count      5.000000    5.000000
mean       3.000000   30.000000
std        1.581139   15.811388
min        1.000000   10.000000
25%        2.000000   20.000000
50%        3.000000   30.000000
75%        4.000000   40.000000
max        5.000000   50.000000
variance   2.500000  250.000000
sem        0.707107    7.071068
sum       15.000000  150.000000
skewness   0.000000    0.000000
kurtosis  -1.200000   -1.200000

#### (ii) remove more
For example, remove `mad`, `variance` and `sem`. The `inplace=False` is the default, which does not change the summary table.

In [7]:
stats

                  A           B
count      5.000000    5.000000
mean       3.000000   30.000000
std        1.581139   15.811388
min        1.000000   10.000000
25%        2.000000   20.000000
50%        3.000000   30.000000
75%        4.000000   40.000000
max        5.000000   50.000000
mad        1.200000   12.000000
variance   2.500000  250.000000
sem        0.707107    7.071068
sum       15.000000  150.000000
skewness   0.000000    0.000000
kurtosis  -1.200000   -1.200000

So the `mad` is still there. If you want to change the table, then use `inplace=True`.

In [8]:
stats.drop(['mad','variance','sem'],inplace=True)
stats

                  A           B
count      5.000000    5.000000
mean       3.000000   30.000000
std        1.581139   15.811388
min        1.000000   10.000000
25%        2.000000   20.000000
50%        3.000000   30.000000
75%        4.000000   40.000000
max        5.000000   50.000000
sum       15.000000  150.000000
skewness   0.000000    0.000000
kurtosis  -1.200000   -1.200000

### (5) Transpose the table
For publication purpose in the journal, we usually need to transpose the above table. Besides, we also just roud to one decimal place.

In [9]:
stats.round(1).T

   count  mean   std   min   25%   50%   75%   max    sum  skewness  kurtosis
A    5.0   3.0   1.6   1.0   2.0   3.0   4.0   5.0   15.0       0.0      -1.2
B    5.0  30.0  15.8  10.0  20.0  30.0  40.0  50.0  150.0       0.0      -1.2